services:
  - type: web
    name: razorpay-fraud-sentinel
    env: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: productionAQ.Ab8RN6KNhzQ-0hNaodTyvKLgyOH4B0UBlOoJBw1GSwflwhCB4Q
      - key: API_KEY
        sync: false
